const planters = [
    {"id":"OBJ1creamM",
    "name":"OBJ 1 - Cream, M",
    "price":15,
    "availability":"in",
    "color":"cream",
    "size":"m",
    "image":"img/planters/Offwhite-Straight-Pot_M.jpeg"},
    {"id":"OBJ1charcoalL",
    "name":"OBJ 1 - Charcoal, L",
    "price":30,
    "availability":"in",
    "color":"charcoal",
    "size":"l",
    "image":"img/planters/black-Straight-Pot-l.jpeg"},
    {"id":"OBJ2creamL",
    "name":"OBJ 2 - Cream, L",
    "price":25,
    "availability":"in",
    "color":"cream",
    "size":"l",
    "image":"img/planters/Off-White-U-Pot_L.jpeg"},
    {"id":"OBJ2charcoalM",
    "name":"OBJ 2 - Charcoal, M",
    "price":10,
    "availability":"in",
    "color":"charcoal",
    "size":"m",
    "image":"img/planters/Black-U-Pot-m.jpeg"},
    {"id":"OBJ1creamL",
    "name":"OBJ 1 - Cream, L",
    "price":30,
    "availability":"in",
    "color":"cream",
    "size":"l",
    "image":"img/planters/Offwhite-Straight-Pot_L.jpeg"},
    {"id":"OBJ2charcoalL",
    "name":"OBJ 2 - Charcoal,L",
    "price":25,
    "availability":"in",
    "color":"charcoal",
    "size":"l",
    "image":"img/planters/Black-U-Pot-L.jpeg"},
    {"id":"OBJ2creamM",
    "name":"OBJ 2 - Cream, M",
    "price":10,
    "availability":"out",
    "color":"cream",
    "size":"m",
    "image":"img/planters/Off-White-U-Pot_M.jpeg"},
    {"id":"OBJ1charcoalM",
    "name":"OBJ 1 - Charcoal, M",
    "price":15,
    "availability":"out",
    "color":"charcoal",
    "size":"m",
    "image":"img/planters/black-Straight-Pot-m.jpeg"}]
const plants = [
    {"id":"JuniperusBonsaiId",
    "name":"Juniperus Bonsai",
    "price":45,
    "availability":"in",
    "type":"bonsai",
    "collection":"japan",
    "image":"img/plants/IMG_8775.jpeg"},
    {"id":"PhyllanthusId",
    "name":"Phyllanthus",
    "price":20,
    "availability":"in",
    "type":"",
    "collection":"hardy",
    "image":"img/plants/IMG_9244.jpeg"},
    {"id":"ChinensisShimpakuId",
    "name":"Chinensis Shimpaku",
    "price":60,
    "availability":"in",
    "type":"bonsai",
    "collection":"japan",
    "image":"img/plants/Kishu_Bonsai_02.jpeg"},
    {"id":"MonsteraDeliciosaId",
    "name":"Monstera Deliciosa",
    "price":25,
    "availability":"in",
    "type":"",
    "collection":"beginner",
    "image":"img/plants/Monstera_ow.jpeg"},
    {"id":"OliveTreeId",
    "name":"Olive Tree",
    "price":35,
    "availability":"in",
    "type":"tree",
    "collection":"japan",
    "image":"img/plants/Olive-Tree-L.jpeg"},
    {"id":"EverfreshTreeId",
    "name":"Everfresh Tree",
    "price":50,
    "availability":"in",
    "type":"tree",
    "collection":"japan",
    "image":"img/plants/Everfresh.jpeg"},
    {"id":"PachiraAquaticaId",
    "name":"Pachira Aquatica",
    "price":15,
    "availability":"out",
    "type":"",
    "collection":"beginner",
    "image":"img/plants/Pachira_Moon_p.jpeg"},
    {"id":"VariegatedBonsaiId",
    "name":"Variegated Bonsai",
    "price":40,
    "availability":"in",
    "type":"bonsai",
    "collection":"japan",
    "image":"img/plants/Wind-Swept_t.jpeg"},]